# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Sat Mar 18 12:05:59 2023)---
runfile('C:/Users/Administrator/.spyder-py3/temp.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/temp.py')
runfile('C:/Users/Administrator/.spyder-py3/temp.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC362 Reasonable.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC362 Simple.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC362 Reasonable.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC528.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC528.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Binarysearch recursive.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Binarysearch recursive.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC362 Simple.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode 36 Sukoku.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode36 set.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Sun Mar 19 14:37:15 2023)---
runfile('C:/Users/Administrator/.spyder-py3/Leetcode305.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/Leetcode305.py')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode305.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Sun Mar 19 16:17:08 2023)---
runfile('C:/Users/Administrator/.spyder-py3/Leetcode305.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/Leetcode305.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode305.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Binarysearch recursive.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode305.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode110.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled2.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode208.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode110.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode208.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode305.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode 208.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Leetcode36 set.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC3 longest substr no repeating char.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode 106.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree1.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/Decision Tree1.py')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree1.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/Decision Tree1.py')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/untitled9.py')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree1.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/Decision Tree1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('E:/anaconda3/lib/site-packages/ipykernel/untitled11.py', wdir='E:/anaconda3/lib/site-packages/ipykernel')
runfile('E:/anaconda3/lib/site-packages/ipykernel/untitled12.py', wdir='E:/anaconda3/lib/site-packages/ipykernel')
runfile('E:/anaconda3/Lib/site-packages/ipykernel/shortest substring.py', wdir='E:/anaconda3/Lib/site-packages/ipykernel')

## ---(Sat Mar 25 09:39:22 2023)---
runfile('E:/anaconda3/Lib/site-packages/ipykernel/untitled0.py', wdir='E:/anaconda3/Lib/site-packages/ipykernel')
runfile('E:/anaconda3/Lib/site-packages/ipykernel/shortest substring.py', wdir='E:/anaconda3/Lib/site-packages/ipykernel')
runfile('E:/anaconda3/Lib/site-packages/ipykernel/untitled0.py', wdir='E:/anaconda3/Lib/site-packages/ipykernel')
runfile('E:/anaconda3/Lib/site-packages/ipykernel/shortest substring1.py', wdir='E:/anaconda3/Lib/site-packages/ipykernel')
runfile('E:/anaconda3/Lib/site-packages/ipykernel/shortest substring.py', wdir='E:/anaconda3/Lib/site-packages/ipykernel')
runfile('E:/anaconda3/Lib/site-packages/ipykernel/untitled1.py', wdir='E:/anaconda3/Lib/site-packages/ipykernel')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC362 Reasonable.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/temp.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Sun Mar 26 14:22:31 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Sun Mar 26 17:24:19 2023)---
runfile('C:/Users/Administrator/.spyder-py3/LC362 Reasonable.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC3 longest substr no repeating char.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC528.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Binarysearch recursive.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode 106.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Decision Tree1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled2.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcards.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcards 3 persons.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcards.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/untitled4.py')
debugfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
runfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
runfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Thu Apr 13 17:08:48 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled4.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled5.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled11.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled13.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled14.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled14.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled15.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled15.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
runfile('C:/Users/Administrator/.spyder-py3/untitled15.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Polonomia print.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled16.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Fri May  5 09:26:37 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode 7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled11.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled11.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled11.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled11.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled13.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Wed May 10 11:03:25 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Fri May 12 13:00:59 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Sat Jun 10 12:57:36 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Mon Jun 12 11:01:49 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Sat Jun 17 10:35:04 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Wed Jul  5 10:13:23 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Thu Jul 20 10:05:45 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode 38.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/island max area.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/island max area.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled11.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/leetcode 17 letterCombinations of a phone.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled19.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/dropbox incorrectPasscodeAttempts.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled21.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled22.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled23.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled24.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Tree in-order iterator.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled26.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled27.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled28.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled29.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled30.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled31.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled32.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled33.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled32.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/magic triple.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled37.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled38.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled39.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled38.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled40.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled42.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled45.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled45.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/LC 10.py')
runfile('C:/Users/Administrator/.spyder-py3/untitled42.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled48.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled49.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled50.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled51.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled52.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled53.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled40.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled39.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled38.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/combinationSum.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled40.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled54.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Folder access 1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/LC 609 Find Duplicate File in System.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/print_all_sum_rec.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled40.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Coin Change 1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/merge pair.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled31.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled29.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled26.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Tree in-order iterator.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/Tree in-order iterator.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Rotate Image.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled21.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled21.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode 17 letterCombinations of a phone.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled13.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled13.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
c
clear
runfile('C:/Users/Administrator/.spyder-py3/numbers of island.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/numbers of island.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/island max area.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/island max area.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled11.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled11.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled56.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled57.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled58.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled58.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled60.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled61.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/Memory DB.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Memory DB.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled63.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled64.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled63.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled64.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled63.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled65.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/playcard 3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled66.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled67.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled70.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled70.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled71.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled71.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled71.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled71.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled71.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled71.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled67.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled68.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled73.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled73.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Fri Aug 11 11:00:26 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled6.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled7.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Sat Aug 12 12:50:16 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled9.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled10.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled8.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled12.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Token bucket.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/Token bucket.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/Token bucket.py')
runfile('C:/Users/Administrator/.spyder-py3/untitled15.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled16.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Token bucket.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled19.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled19.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled19.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled18.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Top m photo.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/Top m photo.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Top m photo.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled22.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Wed Aug 16 08:43:15 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled23.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled24.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled24.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled24.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled24.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled25.py', wdir='C:/Users/Administrator/.spyder-py3')
clear
debugfile('C:/Users/Administrator/.spyder-py3/untitled25.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled26.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Thu Aug 17 16:02:54 2023)---
runfile('C:/Users/Administrator/.spyder-py3/top m photo updated.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled23.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled15.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled16.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled14.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Top m photo.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/untitled28.py')
runfile('C:/Users/Administrator/.spyder-py3/untitled28.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/单词组句.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/单词组句.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Top K.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/Top K.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled3.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled29.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled29.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled30.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled30.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled30.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled31.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled30.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled32.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled33.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled36.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled36.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/untitled35.py')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Binary Tree Elegent.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled37.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled33.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Space Efficient.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Space Efficient.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled33.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Space Efficient.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Binary Tree Elegent.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Space Efficient.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Space Efficient.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Binary Tree Elegent.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/leetcode 38.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/leetcode 38.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Binary Tree Elegent.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/top m photo updated.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Space Efficient.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple with next_id.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Space Efficient.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/Allocator Binary Tree Elegent.py')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Binary Tree Elegent.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Webcrawler.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled39.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled41.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled42.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled43.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Token bucket.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Mon Aug 28 16:31:52 2023)---
runfile('C:/Users/Administrator/.spyder-py3/KV Store.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/untitled44.py')
runfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled45.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/KV Store.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/KV Store.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled46.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/KV Store.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled47.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/untitled48.py')
runfile('C:/Users/Administrator/.spyder-py3/untitled48.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/top m photo updated.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Wed Aug 30 10:13:16 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled48.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Wed Aug 30 15:40:31 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled48.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Wed Aug 30 16:05:34 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled48.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Wed Aug 30 19:01:58 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled45.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled46.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled49.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled46.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled50.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled51.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled52.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled53.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled52.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled53.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled52.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Thu Aug 31 14:01:58 2023)---
runfile('C:/Users/Administrator/.spyder-py3/Token bucket.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Thu Aug 31 14:10:58 2023)---
runfile('C:/Users/Administrator/.spyder-py3/Token bucket.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Thu Aug 31 15:00:24 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled44.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled43.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled49.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Thu Aug 31 19:58:13 2023)---
runfile('C:/Users/Administrator/untitled0.py', wdir='C:/Users/Administrator')
runfile('C:/Users/Administrator/untitled1.py', wdir='C:/Users/Administrator')
runfile('C:/Users/Administrator/.spyder-py3/KV Store.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled13.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled17.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled13.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled24.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/KV Store.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled30.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled31.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled32.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled36.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled37.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled36.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled38.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled41.py', wdir='C:/Users/Administrator/.spyder-py3')
runcell(0, 'C:/Users/Administrator/.spyder-py3/untitled41.py')
runfile('C:/Users/Administrator/.spyder-py3/untitled41.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled45.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled46.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled49.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled46.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled45.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled50.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Tocken_bucket multithreading.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/top m photo updated.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Token bucket.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/MultiThreaded Webcrawler.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled51.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Simple without next_id.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Tue Sep  5 23:38:37 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled1.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled13.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled17.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled17.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled17.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled20.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled24.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled28.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/Allocator Binary Tree Elegent.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/MultiThreaded Webcrawler.py', wdir='C:/Users/Administrator/.spyder-py3')

## ---(Fri Sep 22 09:47:04 2023)---
runfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled0.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled32.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled34.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled36.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
debugfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')
runfile('C:/Users/Administrator/.spyder-py3/untitled35.py', wdir='C:/Users/Administrator/.spyder-py3')